trigger:
  branches:
    include:
      - main
      - dev
  paths:
    exclude:
      - HOK.Elastic.RoleMappingGroupSync/*

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  runtime: 'win-x64'

steps:
- task: UseDotNet@2
  inputs:
    version: '3.1.x'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'HOK.Elastic.FileSystemCrawler.ConsoleProgram/HOK.Elastic.FileSystemCrawler.ConsoleProgram.csproj'
    arguments: '--configuration $(buildConfiguration) -r $(runtime) --version-suffix "ci-build-$(Build.SourceVersion)" --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: '$(Build.BuildNumber)'
    publishLocation: 'Container'