<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Elasticsearch.Net" Version="7.17.0" />
    <PackageReference Include="NEST" Version="7.17.0" />
    <PackageReference Include="NLog.Extensions.Logging" Version="5.3.11" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\HOK.Elastic.FileSystemCrawler\HOK.Elastic.FileSystemCrawler.csproj" />
  </ItemGroup>
</Project>