<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Elasticsearch.Net" Version="7.17.5" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.2" />
    <PackageReference Include="MsgReader" Version="6.0.6" />
    <PackageReference Include="NEST" Version="7.17.5" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="OpenMcdf" Version="3.1.0" />
    <PackageReference Include="RestSharp" Version="113.1.0" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.2" />
    <PackageReference Include="System.DirectoryServices.AccountManagement" Version="10.0.2" />
    <PackageReference Include="System.IO.FileSystem.AccessControl" Version="5.0.0" />
    <PackageReference Include="System.Management" Version="10.0.2" />
    <PackageReference Include="System.Net.NameResolution" Version="4.3.0" />
    <PackageReference Include="System.Net.Primitives" Version="4.3.1" />
    <PackageReference Include="System.Net.Sockets" Version="4.3.0" />
    <PackageReference Include="System.Runtime.Caching" Version="10.0.2" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="10.0.2" />
    <PackageReference Include="System.Text.Json" Version="10.0.2" />
    <PackageReference Include="System.Threading.Tasks.Dataflow" Version="10.0.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\HOK.Elastic.DAL\HOK.Elastic.DAL.csproj" />
  </ItemGroup>
</Project>