trigger:
  branches:
    include:
      - main
      - dev
  paths:
    include:
      - HOK.Elastic.FileSystemCrawler.WebAPI/*
      - HOK.Elastic.FileSystemCrawler/*
      - HOK.Elastic.DAL/*

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  runtime: 'win-x64'

steps:
- task: UseDotNet@2
  inputs:
    version: '3.1.x'

- task: MSBuild@1
  inputs:
    solution: 'HOK.Elastic.FileSystemCrawler.WebAPI/HOK.Elastic.FileSystemCrawler.WebAPI.csproj'
    msbuildArchitecture: 'x64'
    configuration: '$(buildConfiguration)'
    msbuildArguments: '/p:TargetFramework=net6.0-windows /p:PublishDir:$(Build.ArtifactStagingDirectory) /p:RuntimeIdentifier:$(runtime)'
    restoreNugetPackages: true


- task: DownloadSecureFile@1
  inputs:
    secureFile: 'wwwroot.zip'

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '$(Agent.TempDirectory)/wwwroot.zip'
    cleanDestinationFolder: false
    destinationFolder: '$(Build.ArtifactStagingDirectory)/HOK.Elastic.FileSystemCrawler.WebAPI'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/HOK.Elastic.FileSystemCrawler.WebAPI'
    ArtifactName: '$(Build.BuildNumber)'
    publishLocation: 'Container'